@baseUrl = https://localhost:5001

// Get configuration setup
GET {{baseUrl}}/configuration HTTP/1.1

### Get configuration keys
GET {{baseUrl}}/configuration/keys HTTP/1.1

### Generate JWT Token endpoint
# @name token
GET {{baseUrl}}/authorization HTTP/1.1

### Validate token
POST {{baseUrl}}/authorization/validate HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token={{token.response.body.$.token}}

### Token as JSON
POST {{baseUrl}}/authorization/asJson HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token={{token.response.body.$.token}}